### PR TITLE
fix: Fargate example

### PR DESCRIPTION
**Pull request by akoshel**
Subject: Fixing Fargate Example

Description:

Hello there,

I encountered an issue with the Fargate example in the project where it failed to work as expected. I've made several changes that resolved the issue for me and allowed the example to function properly. 

Kindly review and consider merging these adjustments. Thank you!

### CODE REVIEW

**Comment by bryantbiggs** [comment]
can you provide more details on what failed, any error messages, how to reproduce, etc.? I'll try deploying the examples we have later but this did work at one point in time

**Comment by akoshel** [comment]
I couldn't save the errors this time. I'll make an attempt to reproduce them in the next few days.

However, I'd like to bring up a few points for consideration:

1. It appears that the 'instance_iam_role_name' might not be required in the Fargate example, causing confusion.
2. I included 'jobRoleArn' in the JobDefinition since it seems necessary in most scenarios.

**Comment by akoshel** [comment]
Hi @bryantbiggs 
Just reproduced original example and it works. Seems like I had another issues before
I left my PR open with following fixes. I think it could be helpful
1. Added jobRoleArn to JobDefinition
2. Removed instance_iam_role and spot_fleet_iam_role (Fargate example works without this roles)

If you think that this changes is not needed you can close PR
Thanks

**Comment by bryantbiggs** [comment]
> Just reproduced original example and it works.

I'm sorry but I'm not following - are you saying that the example is working as intended now or you were able to reproduce the issue(s) you were experiencing with the example?

**Comment by bryantbiggs** [comment]
closing this for now

**Pull request closed without merging**
